# Generated by Django 3.1.3 on 2021-06-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-id'], 'verbose_name': 'ToDo Title', 'verbose_name_plural': 'ToDos Titles'},
        ),
    ]
